export const size = {
  xhuge: 52,
  huge: 50,
  xxxxtitle: 42,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
  xxxxtiny: 8,
};

export const appRadius = {
  buttonRadius: 25,
  boxRadius: 18,
};

export const family = {
  comorfaBold: 'comfortaBold',
  comorfaLight: 'comfortaBold',
  comorfaRegular: 'comfortaRegular',
  OpenSans_Bold: 'OpenSans-Bold',
  OpenSans_BoldItalic: 'OpenSans-BoldItalic',
  OpenSans_ExtraBold: 'OpenSans-ExtraBold',
  OpenSans_ExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
  OpenSans_Italic: 'OpenSans-Italic',
  OpenSans_Light: 'OpenSans-Light',
  OpenSans_LightItalic: 'OpenSans-LightItalic',
  OpenSans_Medium: 'OpenSans-Medium',
  OpenSans_MediumItalic: 'OpenSans-MediumItalic',
  OpenSans_Regular: 'OpenSans-Regular',
  OpenSans_SemiBold: 'OpenSans-SemiBold',
  OpenSans_SemiBoldItalic: 'OpenSans-SemiBoldItalic',
  // English Fonts
  Poppins_ThinItalic: 'Poppins-ThinItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Light: 'Poppins-Light',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Black: 'Poppins-Black',

  ProximaNova_Regular: 'ProximaNova-Regular',
  ProximaNova_Black: 'ProximaNova-Black',
  ProximaNova_BlackItalic: 'ProximaNova-BlackItalic',
  ProximaNova_Bold: 'ProximaNova-Bold',
  ProximaNova_ExtraboldItalic: 'ProximaNova-ExtraboldItalic',
  ProximaNova_RegularItalic: 'ProximaNova-RegularItalic',
  ProximaNova_SemiboldItalic: 'ProximaNova-SemiboldItalic',
  ProximaNova_ThinItalic: 'ProximaNova-ThinItalic',
  ProximaNova_Light: 'ProximaNova-Light',
  ProximaNova_Medium: 'ProximaNova-Medium',
  ProximaNova_Semibold: 'ProximaNova-SemiBold',

  CircularStd_Regular: 'CircularStd-Regular',
  CircularStd_Medium: 'CircularStd-Medium',
  CircularStd_Bold: 'CircularStd-Bold',
  CircularStd_Black: 'CircularStd-Black',
  CircularStd_BlackItalic: 'CircularStd-BlackItalic',

  Tourney_Regular: 'Tourney-Regular',
};
